# Pour tout push dans le repo
# - déclencher un build d'une nouvelle image docker en utilisant le Dockerfile 
# - et faire un push vers dockerHub

name: build and push image

on: [push]

jobs: 
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: tree
  
      - name: login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: user1/appname:latest
