#Pour tout push dans le repo
#- déclencher un build d'une nouvelle image docker en utilisant le Dockerfile 
#- et faire un psuh vers dockerHub

name: build and push image
on: [push]
jobs: 
 check-bats-version:
   uns-on: ubuntu-latest
   steps:
    -uses: actions/checkout@v3

      #- name: Set up Docker Buildx
        #uses: docker/setup-buildx-action@v1

      #- name: Login to Docker Hub
        #uses: docker/login-action@v1
        #with:
          #username: ${{ secrets.DOCKER_HUB_USERNAME }}
          #password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      #- name: Build and push
        #uses: docker/build-push-action@v2
        #with:
          #context: .
          #file: ./Dockerfile
          #push: true
          #tags: dorianvrn19/getting-started:lasted
          
