name: Build and Push Docker Image

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: getting-started
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      #- name: Set up Docker Buildx
        #uses: docker/setup-buildx-action@v1

      #- name: Login to Docker Hub
        #uses: docker/login-action@v1
        #with:
          #username: ${{ secrets.DOCKER_HUB_USERNAME }}
          #password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      #- name: Build and push
        #uses: docker/build-push-action@v2
        #with:
          #context: .
          #file: ./Dockerfile
          #push: true
          #tags: dorianvrn19/getting-started:lasted
          
