name: package-getting-started-app
on : [push]
jobs:
  package-getting-started-app:
    runs-on: ubuntu-latest
    steps:
      - uses: github/checkout@v2
      

# - checkout le code
# - build et tag image
# - push sur dockerhub
